autolabeler:
  - label: 'chore'
    branch:
      - 'chore.*'
    title:
      - 'chore.*'
  - label: 'bug'
    branch:
      - 'bug.*'
    title:
      - 'bug.*'
  - label: 'feature'
    branch:
      - 'feat.*'
    title:
      - 'feat.*'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    label: 'chore'
change-template: '- $TITLE'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes
  $CHANGES
